<a href="https://colab.research.google.com/github/YuvanBharathi13/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [2]:
import numpy as np

In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.1


## 1.Tensors with tf.constant()

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

In [6]:
vector = tf.constant([1,2,3,4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
matrix1 = tf.constant([[1,2],[3,4],[5,6]],dtype=tf.float16)
matrix1 # changing the data type of the values

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
matrix1.ndim

2

In [12]:
matrix_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
matrix_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [13]:
matrix_3d.ndim

3

### Note
- Scalars = a single number
- Vectors = number with direction
- Matrices = 2 demensional arrays or vectors
- Tensors = Tensors can be thought of as objects that hold multi-dimensional arrays (similar to NumPy arrays), but with added special functionality and optimizations.

## 2.Tensors with tf.Variable()
- tf.Variable() allows you to create tensors that can be modified. Tensors created from
tf.constant() cant be changed, as the name implies.

In [14]:
# creating the same tensors as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# Changing elements in our changeable tensor
changeable_tensor[0] = 7 # this way is not possible, have to be done through a function
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
# using the assign function
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
changeable_tensor.assign_add([10,10])
changeable_tensor # it adds 2 vectors element wise

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([17, 17], dtype=int32)>

### Note
- Rarely in practice will you have to decide whether to use tf.constant() or tf.variable() to create tensors as tensorflow does this for you. But just in case use tf.constant() and change it later on if needed

## 3.Creating Random Tensors

In [19]:
# creating random tensors is used to initially assign weights to the hidden layer nodes
random_1 = tf.random.Generator.from_seed(7)
random_1 = tf.random.normal(shape=(3,3)) # using random numbers from normal distribuition
random_2 = tf.random.Generator.from_seed(7)
random_2 = tf.random.normal(shape=(3,3)) # using random numbers from normal distribuition
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.04864772,  2.2338748 , -1.0759466 ],
        [ 0.53650004, -0.6711165 , -0.6259301 ],
        [-0.21441327, -0.11657184, -0.21126465]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.36036852, -0.17011803,  0.1956936 ],
        [-0.16283302,  2.4860644 , -0.639388  ],
        [ 0.13361934, -1.0077102 , -1.2133868 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [22]:
random_1 = tf.random.uniform(shape=(3,3)) # random numbers generated from a uniform distribuition
random_2 = tf.random.uniform(shape=(3,3))
random_1, random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.5842354 , 0.6814151 , 0.58836424],
        [0.12296402, 0.73690224, 0.63534594],
        [0.83776283, 0.74906886, 0.15325093]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.4998182 , 0.865371  , 0.7394271 ],
        [0.85839844, 0.67766416, 0.52036715],
        [0.39272034, 0.46311748, 0.6741817 ]], dtype=float32)>)

## 4.Shuffling Tensors
- Shuffling is used to spread out the inputs being fed into the neural network to avoid biases

In [26]:
not_shuffled = tf.constant([[4,6,3],[9,3,1],[2,7,0]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 6, 3],
       [9, 3, 1],
       [2, 7, 0]], dtype=int32)>

In [30]:
shuffled = tf.random.shuffle(not_shuffled,)
shuffled # randomly shuffles the values in demension 0, which is the columns. This
# means the values in the same column only get shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 6, 3],
       [2, 7, 0],
       [9, 3, 1]], dtype=int32)>