<a href="https://colab.research.google.com/github/YuvanBharathi13/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [2]:
import numpy as np

In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.1


## 1.Tensors with tf.constant()

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

In [6]:
vector = tf.constant([1,2,3,4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
matrix1 = tf.constant([[1,2],[3,4],[5,6]],dtype=tf.float16)
matrix1 # changing the data type of the values

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
matrix1.ndim

2

In [12]:
matrix_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
matrix_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [13]:
matrix_3d.ndim

3

### Note
- Scalars = a single number
- Vectors = number with direction
- Matrices = 2 demensional arrays or vectors
- Tensors = Tensors can be thought of as objects that hold multi-dimensional arrays (similar to NumPy arrays), but with added special functionality and optimizations.

## 2.Tensors with tf.Variable()
- tf.Variable() allows you to create tensors that can be modified. Tensors created from
tf.constant() cant be changed, as the name implies.

In [14]:
# creating the same tensors as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Changing elements in our changeable tensor
changeable_tensor[0] = 7 # this way is not possible, have to be done through a function
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
# using the assign function
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
changeable_tensor.assign_add([10,10])
changeable_tensor # it adds 2 vectors element wise

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([17, 17], dtype=int32)>

### Note
- Rarely in practice will you have to decide whether to use tf.constant() or tf.variable() to create tensors as tensorflow does this for you. But just in case use tf.constant() and change it later on if needed

## 3.Creating Random Tensors

In [18]:
# creating random tensors is used to initially assign weights to the hidden layer nodes
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,3)) # using random numbers from normal distribuition
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,3)) # using random numbers from normal distribuition
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 ],
        [-0.08857018,  0.69211644,  0.84215707],
        [-0.06378496,  0.92800784, -0.6039789 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 ],
        [-0.08857018,  0.69211644,  0.84215707],
        [-0.06378496,  0.92800784, -0.6039789 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [19]:
random_1 = tf.random.uniform(shape=(3,3)) # random numbers generated from a uniform distribuition
random_2 = tf.random.uniform(shape=(3,3))
random_1, random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.48457193, 0.04450369, 0.74174464],
        [0.11829841, 0.49362445, 0.91997254],
        [0.12817979, 0.13042235, 0.22922397]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.9171287 , 0.62649906, 0.4792949 ],
        [0.9425094 , 0.3221904 , 0.67844284],
        [0.5890869 , 0.5788915 , 0.91441035]], dtype=float32)>)

## 4.Shuffling Tensors
- Shuffling is used to spread out the inputs being fed into the neural network to avoid biases

In [20]:
not_shuffled = tf.constant([[4,6,3],[9,3,1],[2,7,0]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 6, 3],
       [9, 3, 1],
       [2, 7, 0]], dtype=int32)>

In [21]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled # randomly shuffles the values in demension 0, which is the columns. This
# means the values in the same column only get shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 3, 1],
       [4, 6, 3],
       [2, 7, 0]], dtype=int32)>

- The function uses a conjuction of the global seed and the local seed to set the random values. 1. if only the global seed is given and random local seed is used, 2. if only the local seed is given a random global seed is taken, 3. if neither are given both are randomly chosen.

In [22]:
tf.random.set_seed(42) # using global seed
shuffled = tf.random.shuffle(not_shuffled,seed=35) # using local seed
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 3, 1],
       [4, 6, 3],
       [2, 7, 0]], dtype=int32)>

## 5.Tensors from np.array

In [23]:
ones = tf.constant(1,shape=(3,5))
ones

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [24]:
# another way to do it
one1 = tf.ones([3,5],tf.int32)
one1

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [25]:
tf.zeros([5,5],tf.int32)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [26]:
# converting numpy arrays into tensors
arr_np = np.arange(1,25)
arr_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
tensor_of_arr = tf.constant(arr_np,shape=(2,3,4))
tensor_of_arr # reshaping that numpy array into a 3d structure, but make sure
# the number of values in the np.array completely fit the new structure created

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [28]:
# Another shape
tensor_of_arr = tf.constant(arr_np,shape=(3,8))
tensor_of_arr

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

## 6.Tensor Attributes

In [29]:
# Same as in numpy
tens = tf.constant([[7,4,8],[1,0,6],[9,9,2]])
tens

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 4, 8],
       [1, 0, 6],
       [9, 9, 2]], dtype=int32)>

In [30]:
tens.shape

TensorShape([3, 3])

In [31]:
tf.size(tens)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [32]:
tens[0], tens[0].numpy() # converts it to a numpy array

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 4, 8], dtype=int32)>,
 array([7, 4, 8], dtype=int32))

In [33]:
tens.ndim # also referred to as rank

2

## 7.Indexing and Expanding

In [34]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor, rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [35]:
rank_4_tensor[:2,:3,:2]

<tf.Tensor: shape=(2, 3, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
# Getting the first 2 rows of each demension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# creatinf a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
# get the last item of each row
rank_2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [39]:
# adding an extra dimension to the rank 2 tensor using the same numbers, just reshaping
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor ### the 3 dots before is saying let the previous demensions
# remain the same and add a new one to the last demension.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
rank_2_tensor[:,tf.newaxis,:]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [41]:
rank_2_tensor[tf.newaxis,:,:], rank_2_tensor[tf.newaxis,:,:].ndim

(<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4]]], dtype=int32)>,
 3)

In [42]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # expanding the last axis (columns)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor,axis=1) # expanding the row axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

## 8.Manipulating Tensors (tensor operations)

note - `+`,`-`,`*` and `/` operations. For all these operations better to use the built in functions as it is faster and uses the GPU for it.

In [44]:
tensor1 = tf.Variable([[3,7],[8,4]])
tensor2 = tf.Variable([[4,6],[3,5]])
tensor1, tensor2

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[3, 7],
        [8, 4]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[4, 6],
        [3, 5]], dtype=int32)>)

In [45]:
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 70],
       [80, 40]], dtype=int32)>

In [46]:
tf.multiply(tensor1,10) # it is actually tf.math.multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 70],
       [80, 40]], dtype=int32)>

In [47]:
tf.multiply(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 42],
       [24, 20]], dtype=int32)>

In [48]:
tensor3 = tf.Variable([[3],[5]])
tensor3

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[3],
       [5]], dtype=int32)>

In [49]:
tf.multiply(tensor3,tensor2) # as long as it follows the broadcasting rules

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 18],
       [15, 25]], dtype=int32)>

In [50]:
tf.add(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 13],
       [11,  9]], dtype=int32)>

In [51]:
tf.subtract(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  1],
       [ 5, -1]], dtype=int32)>

In [52]:
tf.divide(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.75      , 1.16666667],
       [2.66666667, 0.8       ]])>

## 9.Matrix Multiplication


In [58]:
tensor1, tensor3, tensor1.shape, tensor3.shape

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[3, 7],
        [8, 4]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[3],
        [5]], dtype=int32)>,
 TensorShape([2, 2]),
 TensorShape([2, 1]))

In [56]:
# tf.linalg.matmul
tf.linalg.matmul(tensor1,tensor3)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [44]], dtype=int32)>

In [59]:
# We can ignore the linalg part
tf.matmul(tensor1,tensor3)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [44]], dtype=int32)>

In [60]:
# Matrix multiplication using a python operator
tensor1 @ tensor3

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [44]], dtype=int32)>

In [64]:
X = tf.Variable([[4,5],[6,4],[9,6]])
Y = tf.Variable([[7,4],[2,1],[0,7]])
X,Y

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[4, 5],
        [6, 4],
        [9, 6]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[7, 4],
        [2, 1],
        [0, 7]], dtype=int32)>)

In [67]:
# Multiplication of two 3*2 matrices is not possible, so the transpose
# of the first matrix is taken in order for the multiplication to take place
chumma = tf.matmul(X,Y,transpose_a=True)
chumma

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 85],
       [43, 66]], dtype=int32)>

In [69]:
# notice tf.reshape and tf.transpose shuffle in different ways
X, tf.reshape(X,shape=(2,3)), tf.transpose(X)

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[4, 5],
        [6, 4],
        [9, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [4, 9, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 6, 9],
        [5, 4, 6]], dtype=int32)>)

## 10.Datatype Change