<a href="https://colab.research.google.com/github/YuvanBharathi13/DeepLearning/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1.Datatypes and Attributes

Numpy's main datatype is a ndarray. Ndarray stands for n demensional array

In [29]:
# 1 demsional array or can also be called as an array
# shape = (1,5)
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [30]:
print(type(arr2))

<class 'numpy.ndarray'>


In [31]:
arr2.shape # only for arrays the rows are excluded as its always 1

(5,)

In [6]:
# more than 1 demension therefor called a matrix.
# shape = (3,3)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr3.shape

(3, 3)

In [88]:
# matrix with shape = (2,3,3)
# Axis zero refers to rows and axis 1 refers columns and axis n refers to number of
# matrices stacked on top of the base. In this example there is 1 on top of the base.
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
arr4.shape # these are attributes

(3, 3, 3)

In [10]:
arr1.ndim, arr3.ndim, arr4.ndim # demensions

(1, 2, 3)

In [11]:
arr1.dtype, arr3.dtype, arr4.dtype # data types of the values they hold

(dtype('int64'), dtype('int64'), dtype('int64'))

In [12]:
arr1.size, arr3.size, arr4.size # number of elements in eah of them

(5, 9, 27)

## Creating a DF from np.array

In [13]:
import pandas as pd

In [14]:
df1 = pd.DataFrame(arr3)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
df2 = pd.DataFrame(arr4[0])
df2 # cant make a dataframe with more than 2 demensions

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# 2.Creating Arrays

In [16]:
# Use shift + tab to see a functions documentation
arr1 = np.ones((3,3),int)
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
arr0 = np.zeros((3,3),int)
arr0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
range_array = np.arange(0,100,10)
range_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
random_array = np.random.randint(0,20,size=(2,3))
random_array

array([[ 0,  2, 16],
       [12,  1,  5]])

In [22]:
# All values lie between 0 and 1
random_array_2 = np.random.random((3,3))
random_array_2

array([[0.2573265 , 0.59374782, 0.41879463],
       [0.43603651, 0.37466295, 0.28444761],
       [0.02943917, 0.51275949, 0.23127201]])

In [25]:
# prevents the random numbers from changing evertime the cell is run
np.random.seed(7)
random_array_3 = np.random.random((3,3))
random_array_3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898]])

# 3. Viewing Arrays and matrices

In [26]:
# viewing the unique elements of an numpy array
np.unique(random_array)

array([ 0,  1,  2,  5, 12, 16])

In [32]:
arr2

array([1, 2, 3, 4, 5])

In [33]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr3[1]

array([4, 5, 6])

In [37]:
arr3[1][2]

6

In [34]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [38]:
arr4[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr4[2][1]

array([4, 5, 6])

In [41]:
arr4[2,1,0]

4

In [45]:
# you can also use slicing
arr4[:3,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [50]:
# just a crazy matrix
np.random.seed(7)
arr5 = np.random.randint(10,size=(2,3,4,5))
arr5

array([[[[4, 9, 6, 3, 3],
         [7, 7, 9, 7, 8],
         [9, 8, 7, 6, 4],
         [0, 7, 0, 7, 6]],

        [[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]]],


       [[[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]],

        [[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]]]])

In [51]:
arr5.shape, arr5.ndim

((2, 3, 4, 5), 4)

In [52]:
arr5[1,1,0]

array([3, 0, 4, 8, 6])

In [89]:
arr5[:,:,:,:4] # only the first 4 columns

array([[[[4, 9, 6, 3],
         [7, 7, 9, 7],
         [9, 8, 7, 6],
         [0, 7, 0, 7]],

        [[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]]],


       [[[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]],

        [[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]]]])

# 4.Manipulating and comparing Arrays

## Arithmetic

In [81]:
arr2 = np.array([1.,2.,3.,4.,5.])
arr2

array([1., 2., 3., 4., 5.])

In [90]:
arr1 = np.ones(5,int)
arr1

array([1, 1, 1, 1, 1])

In [91]:
arr1 + arr2

array([2., 3., 4., 5., 6.])

In [66]:
arr2 * arr2

array([ 1,  4,  9, 16, 25])

In [67]:
arr2 * 2

array([ 2,  4,  6,  8, 10])

In [68]:
arr2 + 10

array([11, 12, 13, 14, 15])

In [69]:
arr2 / arr2

array([1., 1., 1., 1., 1.])

In [82]:
arr2 // 3.0 # floor division

array([0., 0., 1., 1., 1.])

In [84]:
arr3 % 4 # modulo function

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]])

In [85]:
np.log(arr3) # Log function

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [87]:
np.exp(arr3) # EXPONENTIAL FUNCTION

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [76]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# each row in the 3*3 matrix is multiplied with arr2
arr2 = [2,3,4]
arr2 * arr3

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [78]:
# arr2 is added to each of the rows in the arr3 matrix
arr2 + arr3

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

## Agreggation
- Note - Manipulating numpy arrays through aggregation. Agreggation is grouping of things into a cluster.

In [94]:
listy = [1,2,3,4,5]
print(type(listy))

<class 'list'>


In [95]:
sum(listy) # from python

15

In [98]:
a1 = np.array([1,2,3,4,5])
np.sum(a1) # from numpy

15