<a href="https://colab.research.google.com/github/YuvanBharathi13/DeepLearning/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

# 1.Datatypes and Attributes

Numpy's main datatype is a ndarray. Ndarray stands for n demensional array

In [43]:
# 1 demsional array or can also be called as an array
# shape = (1,5)
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [44]:
print(type(arr2))

<class 'numpy.ndarray'>


In [45]:
arr2.shape # only for arrays the rows are excluded

(5,)

In [46]:
# more than 1 demension therefor called a matrix.
# shape = (3,3)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr3.shape

(3, 3)

In [48]:
# matrix with shape = (2,3,3)
# Axis zero refers to rows and axis 1 refers columns and axis n refers to number of
# matrices stacked on top of the base. In this example there is 1 on top of the base.
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [49]:
arr4.shape # these are attributes

(3, 3, 3)

In [50]:
arr2.ndim, arr3.ndim, arr4.ndim # demensions

(1, 2, 3)

In [51]:
arr2.dtype, arr3.dtype, arr4.dtype # data types of the values they hold

(dtype('int64'), dtype('int64'), dtype('int64'))

In [52]:
arr2.size, arr3.size, arr4.size # number of elements in eah of them

(5, 9, 27)

## Creating a DF from np.array

In [53]:
import pandas as pd

In [54]:
df1 = pd.DataFrame(arr3)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [55]:
df2 = pd.DataFrame(arr4[0])
df2 # cant make a dataframe with more than 2 demensions

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# 2.Creating Arrays

In [56]:
# Use shift + tab to see a functions documentation
arr1 = np.ones((3,3),int)
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
arr0 = np.zeros((3,3),int)
arr0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
range_array = np.arange(0,100,10)
range_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
random_array = np.random.randint(0,20,size=(2,3))
random_array

array([[ 5, 17, 15],
       [ 7,  9, 11]])

In [60]:
# All values lie between 0 and 1
random_array_2 = np.random.random((3,3))
random_array_2

array([[9.61477013e-01, 9.82540559e-01, 7.74937336e-05],
       [9.13310995e-01, 6.54494630e-01, 3.46017499e-01],
       [4.18563162e-01, 1.69850971e-02, 6.48385768e-01]])

In [61]:
# prevents the random numbers from changing evertime the cell is run
np.random.seed(7)
random_array_3 = np.random.random((3,3))
random_array_3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898]])

# 3. Viewing Arrays and matrices

In [62]:
# viewing the unique elements of an numpy array
np.unique(random_array)

array([ 5,  7,  9, 11, 15, 17])

In [63]:
arr2

array([1, 2, 3, 4, 5])

In [64]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr3[1]

array([4, 5, 6])

In [66]:
arr3[1][2]

6

In [67]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [68]:
arr4[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr4[2][1]

array([4, 5, 6])

In [70]:
arr4[2,1,0]

4

In [71]:
# you can also use slicing
arr4[:3,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [72]:
# just a crazy matrix
np.random.seed(7)
arr5 = np.random.randint(10,size=(2,3,4,5))
arr5

array([[[[4, 9, 6, 3, 3],
         [7, 7, 9, 7, 8],
         [9, 8, 7, 6, 4],
         [0, 7, 0, 7, 6]],

        [[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]]],


       [[[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]],

        [[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]]]])

In [73]:
arr5.shape, arr5.ndim

((2, 3, 4, 5), 4)

In [74]:
arr5[1,1,0]

array([3, 0, 4, 8, 6])

In [75]:
arr5[:,:,:,:4] # only the first 4 columns

array([[[[4, 9, 6, 3],
         [7, 7, 9, 7],
         [9, 8, 7, 6],
         [0, 7, 0, 7]],

        [[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]]],


       [[[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]],

        [[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]]]])

# 4.Manipulating and comparing Arrays

## Arithmetic

In [76]:
arr2 = np.array([1.,2.,3.,4.,5.])
arr2

array([1., 2., 3., 4., 5.])

In [77]:
arr1 = np.ones(5,int)
arr1

array([1, 1, 1, 1, 1])

In [78]:
arr1 + arr2

array([2., 3., 4., 5., 6.])

In [79]:
arr2 * arr2

array([ 1.,  4.,  9., 16., 25.])

In [80]:
arr2 * 2

array([ 2.,  4.,  6.,  8., 10.])

In [81]:
arr2 + 10

array([11., 12., 13., 14., 15.])

In [82]:
arr2 / arr2

array([1., 1., 1., 1., 1.])

In [83]:
arr2 // 3.0 # floor division

array([0., 0., 1., 1., 1.])

In [84]:
arr3 % 4 # modulo function

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]])

In [85]:
np.log(arr3) # Log function

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [86]:
np.exp(arr3) # EXPONENTIAL FUNCTION

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [87]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
# each row in the 3*3 matrix is multiplied with arr2
arr2 = [2,3,4]
arr2 * arr3

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [89]:
# arr2 is added to each of the rows in the arr3 matrix
arr2 + arr3

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

## Agreggation
- Note - Manipulating numpy arrays through aggregation. Agreggation is grouping of things into a cluster.

In [90]:
np.mean(arr2), np.max(arr2), np.min(arr2) # mean, max element and min element

(3.0, 4, 2)

In [91]:
np.std(arr2), np.var(arr2) # standard deviation and variance

(0.816496580927726, 0.6666666666666666)

In [92]:
listy = [1,2,3,4,5]
print(type(listy))

<class 'list'>


In [93]:
sum(listy) # from python

15

In [94]:
a1 = np.array([1,2,3,4,5])
np.sum(a1) # from numpy

15

### Difference between np.sum() and sum() functions  

In [95]:
massive_array = np.random.random(100000)
massive_array.size, type(massive_array)

(100000, numpy.ndarray)

- You can clearly see t he difference in speed below

In [96]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy np.sum()

22.1 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
44.3 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Re-shaping
- Reshaping is really importmant because the structure of data that is fed into the model that you have created has to be a particular way. You cant have data of different structures be fed into the model as it will only recognize the structure you have specified.

In [99]:
np.random.seed(2)
a2 = np.random.randint(10,size=(2,3))
a2

array([[8, 8, 6],
       [2, 8, 7]])

In [106]:
np.random.seed(3)
a3 = np.random.randint(10,size=(2,3,3))
a3

array([[[8, 9, 3],
        [8, 8, 0],
        [5, 3, 9]],

       [[9, 5, 7],
        [6, 0, 4],
        [7, 8, 1]]])

In [109]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

- When comparing 2 arrays, numpy starts with the right most demensions workign its way to the left. Broadcasting will occur if 1. the demensions are equaal or 2. one of the demensions is 1.

In [113]:
a2.shape, a3.shape # with these 2 arrays broadcasting is not possible so reshaping must be done

((2, 3), (2, 3, 3))

In [119]:
a2_reshaped_1 = a2.reshape(2,1,3)
a2_reshaped_1

array([[[8, 8, 6]],

       [[2, 8, 7]]])

In [120]:
a2_reshaped_2 = a2.reshape(2,3,1)
a2_reshaped_2

array([[[8],
        [8],
        [6]],

       [[2],
        [8],
        [7]]])

In [122]:
a2_reshaped_1 * a3

array([[[64, 72, 18],
        [64, 64,  0],
        [40, 24, 54]],

       [[18, 40, 49],
        [12,  0, 28],
        [14, 64,  7]]])

In [123]:
a2_reshaped_2 * a3

array([[[64, 72, 24],
        [64, 64,  0],
        [30, 18, 54]],

       [[18, 10, 14],
        [48,  0, 32],
        [49, 56,  7]]])

## Transposing

In [124]:
a2

array([[8, 8, 6],
       [2, 8, 7]])

In [125]:
a2.T

array([[8, 2],
       [8, 8],
       [6, 7]])

## Dot Product

In [127]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [128]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [129]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [131]:
# Elemental Multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [141]:
# Dot product
np.dot(mat1,mat2) # will not work because the number of columns in mat1 dont match
# the number of rows in mat2. In order for this to work we TRANSPOSE mat2.

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [138]:
mat2 = mat2.T

In [140]:
np.dot(mat1,mat2) # 5*3 and 3*5

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

### Dot Product Example

In [142]:
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[18,  3, 17],
       [19, 19, 19],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11]])

In [143]:
df = pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thurs","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
df

Almond Butter  Peanut Butter  Cashew Butter
Mon               18              3             17
Tues              19             19             19
Wed               14              7              0
Thurs              1              9              0
Fri               10              3             11

In [144]:
price = np.array([10,8,12])
price

array([10,  8, 12])

In [146]:
df_prices = pd.DataFrame(price.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
df_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [148]:
total_sales = np.dot(sales_amount,price.T)
total_sales = total_sales.reshape(5,1)
total_sales

array([[408],
       [570],
       [196],
       [ 82],
       [256]])

In [149]:
df["Total Sales"] = total_sales
df

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon               18              3             17          408
Tues              19             19             19          570
Wed               14              7              0          196
Thurs              1              9              0           82
Fri               10              3             11          256

## Comparison Operators